"use client";
import {useState} from "react";
import {FolderPlus,Pencil,CornerUpRight,Trash2,X,ArrowUp,ArrowDown} from "lucide-react";
import {chapterPath,type StudyChapter} from "./studyTypes";
export type TreeAction={kind:'add'|'edit'|'move'|'delete'|'up'|'down';id:string;subject:boolean;title?:string;color?:string;type?:'folder'|'chapter';parentId?:string|null};
export default function StudyTreeActions({id,subject,title:original,color:originalColor,chapters,subjectId,onAction,onClose}:{id:string;subject:boolean;title:string;color?:string;chapters:StudyChapter[];subjectId:string;onAction:(action:TreeAction)=>void;onClose:()=>void}){
 const [mode,setMode]=useState<TreeAction['kind']|null>(null),[title,setTitle]=useState(original),[color,setColor]=useState(originalColor||'#d5b66a'),[type,setType]=useState<'chapter'|'folder'>('chapter'),[parent,setParent]=useState('');
 const excluded=new Set([id]);let size=0;while(size!==excluded.size){size=excluded.size;chapters.forEach(c=>{if(c.parentId&&excluded.has(c.parentId))excluded.add(c.id);});}
 const finish=(kind:TreeAction['kind'])=>{onAction({kind,id,subject,title:title.trim(),color,type,parentId:parent||null});onClose();};
 return <div className="study-inline-actions" role="group" aria-label={`${original} 관리 영역`}><div className="study-inline-tools"><div>{([{kind:'add',label:'추가',Icon:FolderPlus},{kind:'edit',label:'수정',Icon:Pencil},...(!subject?[{kind:'move',label:'이동',Icon:CornerUpRight}]:[]),{kind:'delete',label:'삭제',Icon:Trash2}] as const).map(({kind,label,Icon})=><button key={kind} aria-pressed={mode===kind} onClick={()=>{setMode(kind as TreeAction['kind']);setTitle(kind==='add'?'':original);setColor(originalColor||'#d5b66a');}}><Icon size={13}/>{label}</button>)}<button aria-label="위로 이동" onClick={()=>finish('up')}><ArrowUp size={13}/></button><button aria-label="아래로 이동" onClick={()=>finish('down')}><ArrowDown size={13}/></button></div><button aria-label="관리 닫기" onClick={onClose}><X size={14}/></button></div>
 {(mode==='add'||mode==='edit')&&<form onSubmit={e=>{e.preventDefault();if(title.trim())finish(mode);}}><div className="study-inline-fields"><input autoFocus aria-label={mode==='add'?'새 하위 목차 이름':'이름'} placeholder="이름" value={title} onChange={e=>setTitle(e.target.value)}/>{mode==='add'&&<select aria-label="목차 종류" value={type} onChange={e=>setType(e.target.value as 'chapter'|'folder')}><option value="chapter">단원</option><option value="folder">폴더</option></select>}<input type="color" aria-label="색상" value={color} onChange={e=>setColor(e.target.value)}/></div><footer><button disabled={!title.trim()}>{mode==='add'?'추가하기':'저장'}</button></footer></form>}
 {mode==='move'&&<div><select aria-label="이동할 목차" value={parent} onChange={e=>setParent(e.target.value)}><option value="">과목 바로 아래</option>{chapters.filter(c=>c.subjectId===subjectId&&!excluded.has(c.id)).map(c=><option key={c.id} value={c.id}>{chapterPath(c.id,chapters)}</option>)}</select><footer><button onClick={()=>finish('move')}>여기로 이동</button></footer></div>}
 {mode==='delete'&&<div><p>이 항목과 하위 목차·문제를 모두 삭제할까요?</p><footer><button className="study-inline-delete" onClick={()=>finish('delete')}>삭제하기</button></footer></div>}
 </div>;
}
