"use client";
import {useEffect,useRef,useState} from "react";
import { Home, Search, FileText } from "lucide-react";
import { Plus, X } from "./StudySymbols";
import {MoreHorizontal} from "./StudySymbols";
import {chapterPath,importance,studyText,type StudySubject,type StudyChapter,type StudyQuestion} from "./studyTypes";
import {useTreeDrag} from "./useTreeDrag";
import StudyTreeActions, {type TreeAction} from "./StudyTreeActions";
import {acquireDocumentOverflow} from "./documentOverflow";
type Panel="contents"|"add"|"search"|"stars"|null;
type Props={onTreeAction:(action:TreeAction)=>void;subjects:StudySubject[];chapters:StudyChapter[];questions:StudyQuestion[];screen:string;subjectId:string;chapterId:string;hidden:boolean;onHome:()=>void;onSubject:(id:string)=>void;onChapter:(id:string)=>void;onQuestion:(id:string)=>void;onAddSubject:()=>void;onAddQuestion:(id:string)=>void;onAddFolder:(subjectId:string,parentId:string|null)=>void;onAddChapter:(subjectId:string,parentId:string|null,title:string)=>void;onManageSubject:(id:string)=>void;onManageChapter:(id:string)=>void;};
export default function StudyNavigation(props:Props){
 const [panel,setPanel]=useState<Panel>(null),[query,setQuery]=useState(''),[stars,setStars]=useState(0),[onlyUnmemorized,setOnlyUnmemorized]=useState(false);
 const [expanded,setExpanded]=useState<string[]>(()=>{try { const saved=JSON.parse(localStorage.getItem('lexdeck-contents-expanded-v1')||'[]');return Array.isArray(saved)?saved.filter((id):id is string=>typeof id==='string'):[]; } catch {return [];} }),[addKind,setAddKind]=useState<'question'|'folder'|'chapter'>('question'),[addSubject,setAddSubject]=useState(''),[addParent,setAddParent]=useState(''),[title,setTitle]=useState('');
 const [managing,setManaging]=useState<string|null>(null);
 const root=useRef<HTMLElement>(null),trigger=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{try{localStorage.setItem('lexdeck-contents-expanded-v1',JSON.stringify(expanded));}catch{}},[expanded]);
 const expandCurrent=()=>{const ids=[props.subjectId];let current=props.chapters.find(c=>c.id===props.chapterId);const seen=new Set<string>();while(current&&!seen.has(current.id)){seen.add(current.id);ids.push(current.id);current=props.chapters.find(c=>c.id===current?.parentId);}setExpanded(value=>Array.from(new Set([...value,...ids.filter(Boolean)])));};
 const close=()=>{setPanel(null);};
 const open=(next:Panel)=>{setManaging(null);if(next==='contents')expandCurrent();setPanel(panel===next?null:next);setQuery('');setStars(0);setOnlyUnmemorized(false);setAddSubject(props.subjectId||props.subjects[0]?.id||'');setAddParent(props.chapters.find(c=>c.id===props.chapterId)?.type==='folder'?props.chapterId:'');setTitle('');setAddKind('question');};
 useEffect(()=>{const contents=()=>setPanel('contents');const close=()=>setPanel(null);window.addEventListener('lexdeck-open-contents',contents);window.addEventListener('popstate',close);return()=>{window.removeEventListener('lexdeck-open-contents',contents);window.removeEventListener('popstate',close);};},[]);
 useEffect(()=>{
  if(!panel||props.hidden)return;
  const previous=document.activeElement as HTMLElement|null;const main=document.querySelector<HTMLElement>('.lex-app');const oldOverflow=main?.style.overflow;const releaseOverflow=acquireDocumentOverflow('hidden');
  if(main)main.style.overflow='hidden';
  root.current?.querySelector<HTMLButtonElement>('[aria-label="메뉴 닫기"]')?.focus({preventScroll:true});
  const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPanel(null);return;}if(e.key==='Tab'&&root.current){const nodes=Array.from(root.current.querySelectorAll<HTMLElement>('button,input,select')).filter(el=>!(el as HTMLButtonElement).disabled);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
  document.addEventListener('keydown',key);return()=>{releaseOverflow();if(main)main.style.overflow=oldOverflow||'';document.removeEventListener('keydown',key);(trigger.current||previous)?.focus({preventScroll:true});};
 },[panel,props.hidden]);
 const dragStatus=useTreeDrag(root,panel==='contents'&&!props.hidden,props.chapters,props.onTreeAction,(id)=>setExpanded(value=>value.includes(id)?value:[...value,id]));
 const navigate=(run:()=>void)=>{close();run();};
 const toggle=(id:string)=>setExpanded(value=>value.includes(id)?value.filter(x=>x!==id):[...value,id]);
 const results=props.questions.filter(q=>{
  const searchable=[q.textHtml,q.explanationHtml,...(q.extraPoints||[]).flatMap(p=>[p.category,p.title,p.descriptionHtml]),props.subjects.find(s=>s.id===q.subjectId)?.name||'',chapterPath(q.chapterId,props.chapters)].map(studyText).join(' ').toLocaleLowerCase();
  return searchable.includes(query.trim().toLocaleLowerCase())&&(panel!=='stars'||!onlyUnmemorized||!q.memorized)&&(panel!=='stars'||importance(q)>0&&(!stars||importance(q)===stars));
 });
 const tree=(sid:string,parent:string|null,seen:string[]=[]):React.ReactNode=>props.chapters.filter(c=>c.subjectId===sid&&c.parentId===parent&&!seen.includes(c.id)).map(c=>{
  const children=props.chapters.some(n=>n.subjectId===sid&&n.parentId===c.id),isOpen=expanded.includes(c.id);
  const isContainer=children||c.type==='folder',ownCount=props.questions.filter(q=>q.chapterId===c.id).length;
  return <div key={c.id}><div data-chapter-id={c.id} className={`study-tree-row ${c.id===props.chapterId?'is-selected':''}`}><button className="study-tree-name" aria-expanded={isContainer?isOpen:undefined} onClick={()=>isContainer?toggle(c.id):navigate(()=>props.onChapter(c.id))}>{(c.icon??(c.type==='folder'?'#':''))!==''&&<span aria-hidden="true" className="study-symbol">{c.icon??'#'}</span>}<span>{c.title}</span>{!isContainer&&<small>{ownCount}개</small>}</button><button aria-label={`${c.title} 관리`} aria-expanded={managing===c.id} onClick={()=>setManaging(managing===c.id?null:c.id)}><MoreHorizontal size={18}/></button>{children&&<button className="study-symbol study-tree-chevron" aria-label={`${c.title} ${isOpen?'접기':'펼치기'}`} aria-expanded={isOpen} onClick={()=>toggle(c.id)}>{isOpen?'△':'▽'}</button>}{!children&&<span className="study-tree-spacer" aria-hidden="true"/>}</div>{managing===c.id&&<StudyTreeActions key={c.id} id={c.id} subject={false} title={c.title} icon={c.icon} desc={c.desc} subjects={props.subjects} chapters={props.chapters} subjectId={sid} onAction={props.onTreeAction} onClose={()=>setManaging(null)}/>} {isContainer&&isOpen&&<div className="study-tree-children">{ownCount>0&&<button className="study-tree-name" onClick={()=>navigate(()=>props.onChapter(c.id))}>이 목차의 문제 <small>{ownCount}개</small></button>}{tree(sid,c.id,[...seen,c.id])}</div>}</div>;
 });
 if(props.hidden)return null;
 return <>
 {panel&&<div className="study-panel-backdrop" onClick={close}><section ref={root} role="dialog" aria-modal="true" aria-label={{contents:'목차',search:'전체 검색',stars:'중요문제',add:'추가'}[panel]} className="study-bottom-panel" onClick={e=>e.stopPropagation()}><header><h2>{{contents:'목차',search:'전체 검색',stars:'중요문제',add:'공부 자료 추가'}[panel]}</h2><button type="button" aria-label="메뉴 닫기" onClick={close}><X size={20}/></button></header><div className="study-panel-scroll overflow-y-auto">
 {panel==='contents'&&<>{dragStatus&&<p className="study-help" role="status">{dragStatus}</p>}{props.subjects.length?props.subjects.map(s=><div className="study-tree-subject" key={s.id}><div className="study-tree-row" data-subject-id={s.id}><button className="study-tree-name" aria-expanded={expanded.includes(s.id)} onClick={()=>toggle(s.id)}><span aria-hidden="true" className="study-symbol">{s.icon??"#"}</span><strong>{s.name}</strong></button><button aria-label={`${s.name} 관리`} aria-expanded={managing===s.id} onClick={()=>setManaging(managing===s.id?null:s.id)}><MoreHorizontal size={18}/></button><button className="study-symbol study-tree-chevron" aria-label={`${s.name} ${expanded.includes(s.id)?'접기':'펼치기'}`} aria-expanded={expanded.includes(s.id)} onClick={()=>toggle(s.id)}>{expanded.includes(s.id)?'△':'▽'}</button></div>{managing===s.id&&<StudyTreeActions key={s.id} id={s.id} subject title={s.name} icon={s.icon} desc={s.desc} subjects={props.subjects} chapters={props.chapters} subjectId={s.id} onAction={props.onTreeAction} onClose={()=>setManaging(null)}/>} {expanded.includes(s.id)&&<div className="study-tree-children">{tree(s.id,null)}</div>}</div>):<p className="study-empty-text">아직 과목이 없어요. 첫 과목을 추가해 주세요.</p>}<button className="study-soft-button" onClick={()=>navigate(props.onAddSubject)}><Plus size={16}/>과목 추가</button></>}
 {(panel==='search'||panel==='stars')&&<><label className="study-search"><Search size={18}/><input type="search" aria-label="전체 문제 검색" placeholder="지문, 해설, 추가 포인트 검색" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="검색 지우기" onClick={()=>setQuery('')}><X size={16}/></button>}</label>{panel==='stars'&&<div className="study-filters"><button aria-pressed={onlyUnmemorized} onClick={()=>setOnlyUnmemorized(!onlyUnmemorized)}>{onlyUnmemorized?'미암기만':'전체'}</button>{[1,2,3].map(value=><button key={value} aria-pressed={stars===value} onClick={()=>setStars(stars===value?0:value)}>{'☆'.repeat(value)}</button>)}</div>}<p className="study-result-count" role="status">{results.length}문제</p>{results.map(q=><button className="study-result" key={q.id} onClick={()=>navigate(()=>props.onQuestion(q.id))}><span className="study-result-heading"><span>{studyText(q.textHtml)}</span>{importance(q)>0&&<small>{'☆'.repeat(importance(q))}</small>}</span><small>{props.subjects.find(s=>s.id===q.subjectId)?.name} → {chapterPath(q.chapterId,props.chapters)}</small><p>{studyText(q.explanationHtml)}</p></button>)}{!results.length&&<p className="study-empty-text">조건에 맞는 문제가 없어요.</p>}</>}
 {panel==='add'&&<><div className="study-add-kinds">{(['question','chapter','folder'] as const).map(kind=><button key={kind} aria-pressed={addKind===kind} onClick={()=>setAddKind(kind)}>{kind==='question'?'문제':kind==='chapter'?'단원':'폴더'}</button>)}</div>{props.subjects.length?<><label className="study-field-label">과목<select aria-label="추가할 과목" value={addSubject} onChange={e=>{setAddSubject(e.target.value);setAddParent('');}}>{props.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{addKind==='question'?<><p className="study-help">문제를 저장할 단원을 선택하세요.</p>{props.chapters.filter(c=>c.subjectId===addSubject&&c.type!=='folder').map(c=><button key={c.id} className="study-add-destination" onClick={()=>navigate(()=>props.onAddQuestion(c.id))}><FileText size={17}/>{chapterPath(c.id,props.chapters)}<Plus size={17}/></button>)}{!props.chapters.some(c=>c.subjectId===addSubject&&c.type!=='folder')&&<button className="study-soft-button" onClick={()=>setAddKind('chapter')}>먼저 단원 만들기</button>}</>:<><label className="study-field-label">위치<select aria-label="상위 목차" value={addParent} onChange={e=>setAddParent(e.target.value)}><option value="">과목 바로 아래</option>{props.chapters.filter(c=>c.subjectId===addSubject).map(c=><option key={c.id} value={c.id}>{chapterPath(c.id,props.chapters)}</option>)}</select></label>{addKind==='chapter'?<><label className="study-field-label">단원 이름<input aria-label="단원 이름" placeholder="예: 제1장 민법 총칙" value={title} onChange={e=>setTitle(e.target.value)}/></label><button className="study-primary-button" disabled={!title.trim()} onClick={()=>navigate(()=>props.onAddChapter(addSubject,addParent||null,title.trim()))}>단원 만들기</button></>:<button className="study-primary-button" onClick={()=>navigate(()=>props.onAddFolder(addSubject,addParent||null))}>폴더 이름과 기호 정하기</button>}</>}</>:<p className="study-empty-text">과목을 먼저 만들면 문제와 단원을 추가할 수 있어요.</p>}<button className="study-soft-button" onClick={()=>navigate(props.onAddSubject)}><Plus size={16}/>새 과목 추가</button></>}
 </div></section></div>}
 <nav className="study-bottom-nav" aria-label="주요 메뉴">{([{label:'홈',target:null},{label:'검색',target:'search'},{label:'추가',target:'add'},{label:'중요문제',target:'stars'},{label:'목차',target:'contents'}] as const).map(({label,target})=><button key={label} type="button" title={label} className={target==='add'?'study-nav-add':''} aria-label={label} aria-current={!panel&&props.screen==='home'&&label==='홈'?'page':undefined} aria-expanded={target?panel===target:undefined} onClick={e=>{trigger.current=e.currentTarget;if(label==='홈')navigate(props.onHome);else open(target);}}>{label==='홈'?<Home aria-hidden="true" size={23} strokeWidth={1.7}/>:target==='search'?<Search aria-hidden="true" size={23} strokeWidth={1.7}/>:<span aria-hidden="true" className="study-symbol">{target==='add'?'+':target==='stars'?'☆':'≡'}</span>}</button>)}</nav>
 </>;
}
